
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing Nuitka"
      - python -m pip install --upgrade pip
      - pip install nuitka
      
  pre_build:
    commands:
      - echo "Creating minimal Python script for compilation"
      - mkdir -p source/credential_provider
      - |
        cat > source/credential_provider/__main__.py << 'EOF'
        import sys
        import keyring
        import certifi
        
        def main():
            print("Hello from credential process")
            return 0
        
        if __name__ == "__main__":
            sys.exit(main())
        EOF
      
  build:
    commands:
      - echo "Starting Nuitka compilation - this should trigger the SSL error"
      - |
        python -m nuitka \
          --standalone \
          --onefile \
          --assume-yes-for-downloads \
          --company-name="Claude Code" \
          --product-name="Claude Code Credential Process" \
          --file-version="1.0.0.0" \
          --product-version="1.0.0.0" \
          --windows-file-description="AWS Credential Process for Claude Code" \
          --include-package=keyring.backends \
          --include-package=certifi \
          --output-filename=credential-process-windows.exe \
          --output-dir=. \
          --remove-output \
          source/credential_provider/__main__.py

artifacts:
  files:
    - credential-process-windows.exe
  name: windows-build-artifacts

