version: 0.2

phases:
  build:
    commands:
      - pip show certifi
      - python -c "import ssl; print(ssl.get_default_verify_paths())"
      - python -c "import urllib.request; urllib.request.urlopen('https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-19.1.1-12.0.0-msvcrt-r2/winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.1-mingw-w64msvcrt-12.0.0-r2.zip', timeout=10)"
